## Deliverable 2. Create a Customer Travel Destinations Map.

In [4]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [6]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,San Patricio,US,28.0170,-97.5169,71.60,88,90,13.80,overcast clouds
1,1,Amuntai,ID,-2.4177,115.2494,91.42,49,33,1.54,scattered clouds
2,2,Port Alfred,ZA,-33.5906,26.8910,66.25,81,0,19.53,clear sky
3,3,Ribeira Grande,PT,38.5167,-28.7000,56.84,74,13,35.70,few clouds
4,4,Aitape,PG,-3.1374,142.3475,84.34,72,100,6.04,overcast clouds

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your vacation? "))
max_temp = float(input("What is the maximum temperature you would like for your vacation? "))

What is the minimum temperature you would like for your vacation? 70
What is the maximum temperature you would like for your vacation? 90

In [10]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_city_df = city_data_df.loc[(city_data_df["Max Temp"]>=min_temp) & (city_data_df["Max Temp"]<=max_temp)]
preferred_city_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,San Patricio,US,28.0170,-97.5169,71.60,88,90,13.80,overcast clouds
4,4,Aitape,PG,-3.1374,142.3475,84.34,72,100,6.04,overcast clouds
5,5,Cabo San Lucas,MX,22.8909,-109.9124,77.00,33,40,11.50,scattered clouds
7,7,Bambous Virieux,MU,-20.3428,57.7575,73.99,100,75,3.44,light rain
9,9,Kapaa,US,22.0752,-159.3190,78.80,69,40,8.05,scattered clouds

In [11]:
# 4a. Determine if there are any empty rows.
preferred_city_df.count()

City_ID                236
City                   236
Country                236
Lat                    236
Lng                    236
Max Temp               236
Humidity               236
Cloudiness             236
Wind Speed             236
Weather Description    236
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
# No EMPTY ROWS FOUND.

In [13]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_city_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,San Patricio,US,71.60,overcast clouds,28.0170,-97.5169,
4,Aitape,PG,84.34,overcast clouds,-3.1374,142.3475,
5,Cabo San Lucas,MX,77.00,scattered clouds,22.8909,-109.9124,
7,Bambous Virieux,MU,73.99,light rain,-20.3428,57.7575,
9,Kapaa,US,78.80,scattered clouds,22.0752,-159.3190,
10,Faanui,PF,81.32,few clouds,-16.4833,-151.7500,
12,Jinji,CN,86.76,clear sky,23.2281,110.8261,
13,Avarua,CK,80.60,scattered clouds,-21.2078,-159.7750,
18,Benito Juarez,MX,71.60,scattered clouds,19.3850,-99.1650,
20,Rikitea,PF,77.99,light rain,-23.1203,-134.9692,

In [15]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except(IndexError):
        print("Hotel not found...skipping")

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
-----------------------------
Data Retrieval Complete
-----------------------------

In [22]:
# Print the top rows from the hotels dataframe
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,San Patricio,US,71.60,overcast clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
4,Aitape,PG,84.34,overcast clouds,-3.1374,142.3475,
5,Cabo San Lucas,MX,77.00,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
7,Bambous Virieux,MU,73.99,light rain,-20.3428,57.7575,Casa Tia Villa
9,Kapaa,US,78.80,scattered clouds,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
10,Faanui,PF,81.32,few clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
12,Jinji,CN,86.76,clear sky,23.2281,110.8261,
13,Avarua,CK,80.60,scattered clouds,-21.2078,-159.7750,Paradise Inn
18,Benito Juarez,MX,71.60,scattered clouds,19.3850,-99.1650,Hotel Novit
20,Rikitea,PF,77.99,light rain,-23.1203,-134.9692,Pension Maro'i

In [28]:
# Fill empty cells in Hotel Name column with NaN
import numpy as np
hotel_df['Hotel Name'] = hotel_df['Hotel Name'].replace("", np.NaN)
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,San Patricio,US,71.60,overcast clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
4,Aitape,PG,84.34,overcast clouds,-3.1374,142.3475,NaN
5,Cabo San Lucas,MX,77.00,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
7,Bambous Virieux,MU,73.99,light rain,-20.3428,57.7575,Casa Tia Villa
9,Kapaa,US,78.80,scattered clouds,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
10,Faanui,PF,81.32,few clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
12,Jinji,CN,86.76,clear sky,23.2281,110.8261,NaN
13,Avarua,CK,80.60,scattered clouds,-21.2078,-159.7750,Paradise Inn
18,Benito Juarez,MX,71.60,scattered clouds,19.3850,-99.1650,Hotel Novit
20,Rikitea,PF,77.99,light rain,-23.1203,-134.9692,Pension Maro'i

In [32]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(axis=0, subset=['Hotel Name'])
clean_hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,San Patricio,US,71.60,overcast clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
5,Cabo San Lucas,MX,77.00,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
7,Bambous Virieux,MU,73.99,light rain,-20.3428,57.7575,Casa Tia Villa
9,Kapaa,US,78.80,scattered clouds,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
10,Faanui,PF,81.32,few clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
13,Avarua,CK,80.60,scattered clouds,-21.2078,-159.7750,Paradise Inn
18,Benito Juarez,MX,71.60,scattered clouds,19.3850,-99.1650,Hotel Novit
20,Rikitea,PF,77.99,light rain,-23.1203,-134.9692,Pension Maro'i
27,Toamasina,MG,71.60,light rain,-18.1667,49.3833,Hotel H1
32,Rockport,US,71.60,mist,28.0206,-97.0544,Holiday Inn Express & Suites Rockport - Bay View

In [44]:
#Check for null values in clean_hotel_df.
clean_hotel_df.isnull().sum()

City                   0
Country                0
Max Temp               0
Weather Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [38]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_Vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [42]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country Code</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [43]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))